# Generated by Django 3.2.6 on 2022-06-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220627_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('num_players', models.IntegerField()),
                ('players', models.ManyToManyField(to='accounts.Profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.tournamenttype')),
            ],
        ),
    ]
